### ISSUE TITLE
Hi, How to I run the code using BFM or FLAME ?

### ISSUE THREAD

**Issue by ForrestPi** [kanonet/face-avatar-reconstruction#1]
Hi, I have not FexMM, How should I change the code with BFM or FLAME ?

**Comment by kanonet** [comment]
Hi!
I just made some commits, that improve texture reconstruction support for BFM2017, FLAME and FaceGen. But please be aware, that this is almost untested. However, you will definitely get best results using FexMM.
I also added more details on setup and usage of this framework. Please have a look at the readme again, hopefully everything is explained now.
Basically it is this: convert models, place everything in the correct directories, write your code or modify the example code.  You can select your preferred model using the ModelType enum when setting up the reconstruction pipeline.
Please let me know if something is not lined out clearly.

**Comment by ForrestPi** [comment]
@kanonet  thanks so much

**Comment by mgrewe** [comment]
We are going to release the full version of our FexMM including Identity and Expression variations soon. Find a description of the FexMM here (https://doi.org/10.3389/frvir.2021.619811). 
If you plan to use this model, please visit https://opus4.kobv.de/opus4-zib/frontdoor/index/index/docId/8532 to learn how to obtain the model.

**Comment by ForrestPi** [comment]
@mgrewe thanks
